services:
  php:
    container_name: app
    image: yiisoftware/yii2-php:8.4-fpm-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    links:
      - mysql

  mysql:
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d